### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by codyoss**
Updated the readme to refer to the correct context.

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Hi!

Glad to see you here @codyoss

Basically, the thing you fixed is actually supported to make your migrations easier :)

**Comment by kirillDanshin** [comment]
@codyoss it's supported in [this lines](https://github.com/gramework/gramework/blob/ff9b9a8a4f386564834a53feb9bfd7af6a8184ea/router.go#L109) :)

**Comment by codyoss** [comment]
Ah icic, well I think if you are going to do that in the readme I would either add a comment or say something in the description above. Without diving into the lib I don't think most people would catch onto that. I will close this. Cool lib!

**Comment by kirillDanshin** [comment]
thanks for your feedback and help :)

feel free to add comments and update readme, it will be huge help for the project 'cause I don't have enough time right now to update the docs

**Pull request closed without merging**
